# Generated by Django 2.1.1 on 2019-02-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='saved_location',
            new_name='saved_locations',
        ),
    ]
