# Generated by Django 2.1.7 on 2019-02-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190216_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lng',
            new_name='long',
        ),
    ]
